'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(), _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")> _
Partial Friend NotInheritable Class LayoutSettings
    Inherits Global.System.Configuration.ApplicationSettingsBase

    Private Shared defaultInstance As LayoutSettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New LayoutSettings()), LayoutSettings)

    Public Shared ReadOnly Property [Default]() As LayoutSettings
        Get
            Return defaultInstance
        End Get
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property LogicalLayout() As String
        Get
            Return CType(Me("LogicalLayout"), String)
        End Get
        Set(value As String)
            Me("LogicalLayout") = Value
        End Set
    End Property

    <Global.System.Configuration.UserScopedSettingAttribute(), _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), _
     Global.System.Configuration.DefaultSettingValueAttribute("")> _
    Public Property ViewsLayout() As String
        Get
            Return CType(Me("ViewsLayout"), String)
        End Get
        Set(value As String)
            Me("ViewsLayout") = Value
        End Set
    End Property
End Class
